apiVersion: batch/v1
kind: Job
metadata:
  name: counter-job-green
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: client
        image: 055315558257.dkr.ecr.us-east-1.amazonaws.com/prm-metrics-counter-job:dev-latest
        imagePullPolicy: "Always"
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: jobmanager
        command: ["flink", "run", "-d", "/opt/CounterJob_deploy.jar"]
        args: [
          "--kafkaSecurityProtocol=SSL",
          "--bootstrap.servers=b-1.prm-dev-metrics.kb3o24.c3.kafka.us-east-1.amazonaws.com:9094,b-2.prm-dev-metrics.kb3o24.c3.kafka.us-east-1.amazonaws.com:9094,b-3.prm-dev-metrics.kb3o24.c3.kafka.us-east-1.amazonaws.com:9094",
          "--s3Bucket=prm-dev-event-logs",
          "--jobLabel=green",

          #"--wipe",  ### IMPORTANT: uncomment when backfilling!

          "--parallelism=1",
          # 120 = We don't expect to have to scale dev much.
          "--maxParallelism=120",
          # Setting to 0 writes all values. Setting to -1 uses the process time.  
          "--counterOutputStartTimestamp=0",

          # DB num = {blue: 5, green: 0}
          "--counterService=redis://prm-dev-metrics-counters.x1t9xw.0001.use1.cache.amazonaws.com:6399/0",

          # Backfill flag
          # "--startFromEarliest",
          # "--checkpointInterval=PT1H",
        ]
        # We use specific mounts so we can map in log4j-cli.properties.
        # Otherwise, we need to modify the Helm chart directly.
        # Long-term, we the Flink client jobs should not reuse the config map.
        volumeMounts:
        - name: flink-config
          mountPath: /opt/flink/conf/flink-conf.yaml
          subPath: flink-conf.yaml
        - name: flink-config
          mountPath: /opt/flink/conf/flink-conf-taskmanager.yaml
          subPath: flink-conf-taskmanager.yaml
        - name: flink-config
          mountPath: /opt/flink/conf/log4j.properties
          subPath: log4j.properties
        - name: flink-config
          mountPath: /opt/flink/conf/security.properties
          subPath: security.properties
        - name: flink-cli-config
          mountPath: /opt/flink/conf/log4j-cli.properties
          subPath: log4j-cli.properties
      restartPolicy: Never
      serviceAccountName: ""
      volumes:
      - name: flink-config
        configMap:
          name: flink-config
          items:
            - key: flink-conf.yaml
              path: flink-conf.yaml
            - key: flink-conf-taskmanager.yaml
              path: flink-conf-taskmanager.yaml
            - key: log4j.properties
              path: log4j.properties
            - key: security.properties
              path: security.properties
      - name: flink-cli-config
        configMap:
          name: flink-cli-config
          items:
            - key: log4j-cli.properties
              path: log4j-cli.properties
status: {}
