apiVersion: batch/v1
kind: Job
metadata:
  name: counter-job-green-tmp
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: client
        image: 055315558257.dkr.ecr.us-east-1.amazonaws.com/prm-metrics-counter-job:dd423bb4
        imagePullPolicy: "Always"
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: jobmanager
        command: ["flink", "run", "-d", "/opt/CounterJob_deploy.jar"]
        args: [
          "--kafkaSecurityProtocol=SSL",
          "--bootstrap.servers=b-1.ddd-prod-metrics.ex7o7h.c3.kafka.us-east-1.amazonaws.com:9094,b-2.ddd-prod-metrics.ex7o7h.c3.kafka.us-east-1.amazonaws.com:9094,b-3.ddd-prod-metrics.ex7o7h.c3.kafka.us-east-1.amazonaws.com:9094",
          "--s3Bucket=ddd-prod-event-logs",
          "--jobLabel=green-tmp",
          "--overrideInputLabel=green",

          #"--wipe",  ### IMPORTANT: uncomment when backfilling!

          # Captures most of the queries.
          # See saved Athena query "ddd counter query coverage"
          # Only about 10k query strings over a 7 day window.  Includes 98% of results.
          "--searchQueryWindowMinThreshold=10",
          "--no-hourlyQuery",
          "--no-lastUserQueryEvents",
          "--parallelism=7",
          "--maxParallelism=120",
          # Setting to 0 writes all values.
          "--counterOutputStartTimestamp=0",

          # USING TEMP DB NUMBER OF 1
          "--counterService=redis://ddd-prod-metrics-counters-group.x1t9xw.ng.0001.use1.cache.amazonaws.com:6399/1",

          # Backfill flag
          # (GMT): October 1, 2022 12:00:00 AM
          "--startFromTimestamp=1664582400000",
          #"--checkpointInterval=PT15M",
        ]
        # We use specific mounts so we can map in log4j-cli.properties.
        # Otherwise, we need to modify the Helm chart directly.
        # Long-term, we the Flink client jobs should not reuse the config map.
        volumeMounts:
        - name: flink-config
          mountPath: /opt/flink/conf/flink-conf.yaml
          subPath: flink-conf.yaml
        - name: flink-config
          mountPath: /opt/flink/conf/flink-conf-taskmanager.yaml
          subPath: flink-conf-taskmanager.yaml
        - name: flink-config
          mountPath: /opt/flink/conf/log4j.properties
          subPath: log4j.properties
        - name: flink-config
          mountPath: /opt/flink/conf/security.properties
          subPath: security.properties
        - name: flink-cli-config
          mountPath: /opt/flink/conf/log4j-cli.properties
          subPath: log4j-cli.properties
      restartPolicy: Never
      serviceAccountName: ""
      volumes:
      - name: flink-config
        configMap:
          name: flink-config
          items:
            - key: flink-conf.yaml
              path: flink-conf.yaml
            - key: flink-conf-taskmanager.yaml
              path: flink-conf-taskmanager.yaml
            - key: log4j.properties
              path: log4j.properties
            - key: security.properties
              path: security.properties
      - name: flink-cli-config
        configMap:
          name: flink-cli-config
          items:
            - key: log4j-cli.properties
              path: log4j-cli.properties
status: {}
