# Local values.
# Connects to MinIO.
# Uses values for this project.
# https://github.com/riskfocus/helm-charts-public/tree/master/flink

flink:
  params: |+
    # Lower managed memory since overall memory is lower.
    taskmanager.memory.managed.fraction: 0.5
    s3a.endpoint: http://minio:9000
    s3a.path.style.access: true
    s3a.access-key: YOURACCESSKEY
    s3a.secret-key: YOURSECRETKEY
    s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
    state.checkpoints.dir: s3a://promoted-event-logs/checkpoints
    state.savepoints.dir: s3a://promoted-event-logs/savepoints
    #
    # Uncomment to print Metrics to logs.
    #metrics.reporter.slf4j.factory.class: org.apache.flink.metrics.slf4j.Slf4jReporterFactory
    #metrics.reporter.slf4j.interval: 60 SECONDS
    #
    # Enable JMX extensions to allow for java profiling using tools like visualvm.
    # After uncommenting this line and restarting flink taskmanager in your minikube to
    # include these flags, simply port forward the jmx port (1099) using kubectl:
    #   kubectl -n $NAMESPACE port-forward flink-taskmanager-0 1099
    # and connect there.
    #env.java.opts.taskmanager: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
    s3.entropy.key: _entropy_
    s3.entropy.length: 4
    client.timeout: 1min
    akka.ask.timeout: 1min
    # Default=15.  The default is too low.
    fs.s3a.connection.maximum: 100
taskmanager:
  replicaCount: 1
  numberOfTaskSlots: 5
  memoryProcessSize: 2g
  memoryFlinkSize:
  persistent:
    size: 5Gi
  resources:
    limits:
      cpu: 1000m
      # cpu: 2000m
      # memory: 8000Mi
jobmanager:
  livenessProbe.periodSeconds: 60
