apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: log-generator
  name: log-generator
spec:
  # Delete the job if it has been one day.  It's likely not useful a day later.
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: bazel/pipeline/src/main/java/ai/promoted/metrics/logprocessor/fakedatagenerator:LogGenerator_image
        command: ["java", "-Dlog4j.configurationFile=/log4j.properties", "-jar", "LogGenerator_deploy.jar"]
        # Create fewer events for local development.  About 10k insertions, etc.
        args: [
          "--users=10",
          "--viewsPerSession=10",
          "--responseInsertionsPerRequest=10",
          "--setupForInferredIds",
          "--miniSdkRate=0.2",
          "--shadowTrafficRate=1.0",
          # To write older event_api_timestamp data.
          # "--startEventApiTimestamp=1669363303000",
        ]
        volumeMounts:
        - name: log-generator-config
          mountPath: /log4j.properties
          subPath: log4j.properties
      restartPolicy: OnFailure
      serviceAccountName: ""
      volumes:
      - name: log-generator-config
        configMap:
          name: log-generator-config
          items:
            - key: log4j.properties
              path: log4j.properties
  backoffLimit: 3
status: {}
