apiVersion: v1
kind: Service
metadata:
  name: metrics-api
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: metrics-api
