apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-api
  labels:
    app: metrics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-api
  template:
    metadata:
      labels:
        app: metrics-api
    spec:
      containers:
        - name: metrics-api
          image: bazel/api/main:EventAPI_image
          args: ["main"]
          env:
            - name: EVENT_KAFKA_BROKERS
              value: "kafka:9092"
            - name: KAFKA_DATASET
              value: "aaa-dev"
            - name: DOCKER_LAMBDA_STAY_OPEN
              value: "1"
            - name: PLATFORM
              value: "aaa"
            - name: PLATFORM_ENV
              value: "aaa-dev"
            # Also make sure to update metrics/config
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "250Mi"
          ports:
            - containerPort: 9001
